# Generated by Django 3.2.8 on 2021-10-24 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Studentdatabse',
            new_name='Employee',
        ),
    ]
